#include <stdlib.h>
#include "30.h"
#include "unity.h"

void setUp(void)
{
}

void tearDown(void)
{
}

void test_doublearraysize_null(void) {
	unsigned size = 0;
	char *string = doubleArraySize(NULL, &size);	
	TEST_ASSERT_EQUAL_UINT(0, size);
	TEST_ASSERT_NULL(string);
	free(string);
}

void test_doublearraysize_empty(void) {
	unsigned size = 0;
	char *string = doubleArraySize("", &size);	
	TEST_ASSERT_EQUAL_UINT(0, size);
	TEST_ASSERT_NULL(string);
	free(string);
}

void test_doublearraysize_a(void) {
	unsigned size = 1;
	char *string = doubleArraySize("A", &size);	
	TEST_ASSERT_EQUAL_UINT(2, size);
	char expected2[2] = "A";
	TEST_ASSERT_EQUAL_MEMORY_ARRAY(expected2, string, 2, sizeof(char));
	free(string);
}

void test_doublearraysize_alphabet(void) {
	unsigned size = 26;
	char *string = doubleArraySize("ABCDEFGHIJKLMNOPQRSTUVWXYZ", &size);	
	TEST_ASSERT_EQUAL_UINT(52, size);
	char expected1[52] = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	TEST_ASSERT_EQUAL_MEMORY_ARRAY(expected1, string, 52, sizeof(char));
	free(string);
}

void test_stringlength_null(void) {
	TEST_ASSERT_EQUAL_UINT(0, stringLength(NULL));
}

void test_stringlength_empty(void) {
	TEST_ASSERT_EQUAL_UINT(0, stringLength(""));
}

void test_stringlength_a(void) {
	TEST_ASSERT_EQUAL_UINT(1, stringLength("A"));
}

void test_stringlength_alphabet(void) {
	TEST_ASSERT_EQUAL_UINT(26, stringLength("ABCDEFGHIJKLMNOPQRSTUVWXYZ"));
}

void test_getfilteredstring_comp(void) {
	char *error = NULL;
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", &error);
	TEST_ASSERT_EQUAL_STRING("MATHEMATICS", string);
	TEST_ASSERT_NULL(error);
	free(string);
}

void test_getfilteredstring_comp183(void) {
	char *error = NULL;
	freopen("30test2.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", "ABCDEFGHIJKLMNOPQRSTUVWXYZ", &error);
	TEST_ASSERT_EQUAL_STRING("Found invalid character", error);
	TEST_ASSERT_NULL(string);
	free(string);
}

//////////

void test_doublearraysize_nullsize(void) {
	char *string = doubleArraySize(NULL, NULL);	
	TEST_ASSERT_NULL(string);
	free(string);
}

void test_getfilteredstring_nullprompt(void) {
	char *error = NULL;
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString(NULL, NULL, &error);
	TEST_ASSERT_NULL(string);
	TEST_ASSERT_EQUAL_STRING("Found invalid character", error);
	free(string);
}

void test_getfilteredstring_nullfilter(void) {
	char *error = NULL;
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", NULL, &error);
	TEST_ASSERT_NULL(string);
	TEST_ASSERT_EQUAL_STRING("Found invalid character", error);
	free(string);
}

void test_getfilteredstring_emptyfilter(void) {
	char *error = NULL;
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", "", &error);
	TEST_ASSERT_NULL(string);
	TEST_ASSERT_EQUAL_STRING("Found invalid character", error);
	free(string);
}

void test_getfilteredstring_nullerror(void) {
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", "", NULL);
	TEST_ASSERT_NULL(string);
	free(string);
}

void test_getfilteredstring_duplicatefilter(void) {
	char *error = NULL;
	freopen("30test1.txt", "r", stdin);
	char *string = getFilteredString("Enter the course code:\n", "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZABCDEFGHIJKLMNOPQRSTUVWXYZ", &error);
	TEST_ASSERT_EQUAL_STRING("MATHEMATICS", string);
	TEST_ASSERT_NULL(error);
	free(string);
}

void test_getFilteredString_largeInput(void) {
	char *error = NULL;
	freopen("30test3.txt", "r", stdin);
	char *string = getFilteredString("Enter the web page:\n", "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789", &error);
	TEST_ASSERT_EQUAL_STRING("DOCTYPEhtmlhtmllangenheadtitleCamosunCollegetitlemetahttpequivcontenttypecontenttexthtmlcharsetutf8metanamekeywordscontentmetanamedescriptioncontentLocatedinVictoriaBritishColumbiaCanadaCamosunCollegeoffersuniversitycoursesandprogramsdiplomasdegreesandcertificationinArtsScienceBusinessHealthSportsTradesTechnologiesandmoremetanamegooglesiteverificationcontentDWLqT9UxnW0iJE5D9TWN3uu6vrk3GgiDphNYnqSTkwlinkrelstylesheethrefcdncamosuncabootstrapcurrentcssbootstrapmincsstypetextcssmediascreenlinkrelstylesheethreftemplatecsscamosuncsstypetextcssmediascreenlinkrelstylesheethreftemplatecsscamosunprintcsstypetextcssmediaprintifltIE9linkrelstylesheettypetextcsshreftemplatecsscamosunie8cssendifscripttypetextjavascriptvargaqgaqgaqpushsetAccountUA6397421gaqpushtrackPageviewfunctionvargadocumentcreateElementscriptgatypetextjavascriptgaasynctruegasrchttpsdocumentlocationprotocolhttpssslhttpwwwgoogleanalyticscomgajsvarsdocumentgetElementsByTagNamescript0sparentNodeinsertBeforegasscriptheadbodydividlogoPrintimgsrctemplateimageslogoscamosunlogoprintpngaltCamosunlogoforprintdivdivclassminiwrapperfixdivdividheaderdivclasscontainerdivclassrowdivclassspan3ahreftitleCamosunhomepageimgsrctemplateimageslogoscamosunwhitepngaltCamosunlogoidlogoclasspullleftadivdivclassspan9idquickNavulclassnavnavpillspullrightliahrefHomealiliahrefcamlinkCamlinkaliliahrefonlinecamosuncaD2LaliliahreflibraryLibraryaliliahrefcontactContactusaliulformclassformsearchpullrightidquickSearchactionsearchinputtypetextclasssearchqueryinputxlargenameqidqplaceholderSearchcamosuncaformdivdivdivdivdividmainNavclassnavbardivclassnavbarinnerdivclasscontainerulclassnavidcamNavBarliclasscamNavTabahrefaboutAboutUsadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionAboutUsliliahrefaboutAboutCamosunaliliahrefaboutdirectoryhtmlAdministrativeDepartmentsaliliahrefalumniAlumnialiliahrefabouttransportationparkingcampusmapshtmlCampusMapsaliliahrefcareersCareersatCamosunaliliahreffoundationFoundationaliliahrefaboutinstitutionalresearchInstitutionalResearchandPlanningaliliahrefnewsmediacentreMediaCentrealiliahrefaboutpoliciespolicieshtmlPoliciesaliliahrefabouttradescentreTradesEducationandInnovationComplexaliliclasssectionCommitmentsliliahrefaboutdiversityDiversityaliliahrefaboutindigenizationIndigenizationaliliahrefaboutmentalhealthStudentMentalHealthandWellbeingaliliahrefsustainabilitySustainabilityaliuldivdivclasscolumnulclassunstyledliclasssectionSchoolsliliahreflearnschoolindigenouseducationcommunityconnectionsCentreforIndigenousEducationandCommunityConnectionsaliliahreflearnschoolsportexerciseeducationCentreforSportandExerciseEducationaliliahreflearnschoolaccessSchoolofAccessaliliahreflearnschoolartsscienceSchoolofArtsandSciencealiliahreflearnschoolbusinessSchoolofBusinessaliliahreflearnschoolhealthhumanservicesSchoolofHealthandHumanServicesaliliahreflearnschooltradestechnologySchoolofTradesandTechnologyaliuldivdivliliclasscamNavTabahreflearnProgramsampCoursesadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionAreasofStudyliliahreflearnareasacademicupgradinghtmlAcademicUpgradingaliliahreflearnareasadvancedstudieshtmlAdvancedStudiesaliliahreflearnareasartshtmlArtsandLanguagealiliahreflearnareasbusinesshtmlBusinessaliliahreflearnareascomputersengineeringhtmlComputersandEngineeringaliliahreflearnareasemploymentpreparationhtmlEmploymentPreparationaliliahreflearnareasenglishsecondlanguagehtmlEnglishasaSecondLanguagealiliahreflearnareashealthhumanserviceshtmlHealthandHumanServicesaliliahreflearnareasindigenoushtmlIndigenousaliliahreflearnareassciencetechnologyhtmlMathScienceandTechnologyaliliahreflearnareasonlinehtmlOnlineOptionsaliliahreflearnareassportexercisehtmlSportandExercisealiliahreflearnareastradesapprenticeshipshtmlTradesandApprenticeshipsaliliahreflearnareasuniversitytransferoptionshtmlUniversityTransferOptionsaliuldivdivclasscolumnulclassunstyledliclasssectionProgramandCourseListsliliahrefcealphaindexhtmlContinuingEducationCoursesAZaliliahreflearnsouthislandpartnershipDualCreditSIPaliliahreflearnazProgramsandCoursesAZaliliclasssectionRelatedInformationliliahrefservicesadmissionsAdmissionsaliliahreflearncalendarcurrentArchivedCalendarsaliliahrefservicesfinancialaidFinancialAidandAwardsaliliahreflearnfeesTuitionandFeesaliuldivdivliliclasscamNavTabahrefservicesStudentServicesadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionGettingStartedliliahrefservicesadmissionsAdmissionsaliliahrefservicesassessmentcentreAssessmentandTestingaliliahrefservicesfinancialaidFinancialAidandAwardsaliliahrefservicesregistrationRegistrationaliliahrefservicesstudentrecordstransfercredithtmlTransferCreditaliliahreflearnfeesTuitionandFeesaliliclasssectionCurrentStudentsliliahrefhttpcamosunstudentorgCamosunCollegeStudentSocietyiclassiconexternallinktitleLinkonadifferentsiteialiliahrefcurrentclasscancellationshtmlClassCancellationsaliliahrefservicesstudentrecordscrcCriminalRecordChecksaliliahrefeventsgradGraduationaliliahrefeventsimportantdateshtmlImportantDatesaliliahrefservicesstudentrecordstranscriptshtmlTranscriptsaliuldivdivclasscolumnulclassunstyledliclasssectionPlanYourEducationliliahrefservicesacademicadvisingAcademicAdvisingaliliahrefservicescooperativeeducationstudentemploymentcoopstudentsCoopEducationaliliahreflearnsouthislandpartnershipDualCreditaliliahrefinternationalstudyabroadStudyAbroadaliliclasssectionOnCampusliliahrefhttpcamosuncollegebookstorecaBookstoreiclassiconexternallinktitleLinkonadifferentsiteialiliahrefserviceschildcareChildCarealiliahrefservicescafeteriaCafeteriasaliliahrefservicesitsITServicesaliliahrefservicesprintshopPrintshopaliliahrefservicesfacilityrentalsstudentandCCSSroombookinghtmlRoomBookingsaliliahrefservicescooperativeeducationstudentemploymentstudentsalumniStudentEmploymentaliliahrefabouttransportationparkingTransportationandParkingaliuldivdivclasscolumnulclassunstyledliclasssectionHealthServicesliliahreflearnprogramssportexercisetherapyclinichtmlAthleticandExerciseTherapyClinicaliliahrefservicescounsellingcentreCounsellingaliliahreflearnschoolhealthhumanservicesdentalclinicDentalClinicaliliahrefsportsfitnessrecreationFitnessandRecreationaliliahrefhttpcamosunstudentorghealthanddentalHealthandDentalBenefitsiclassiconexternallinktitleLinkonadifferentsiteialiliclasssectionAcademicSupportliliahrefservicesdisabilityresourcecentreDisabilityResourceCentrealiliahrefserviceshelpcentresHelpCentresaliliahrefserviceslibraryLibraryaliuldivdivliliclasscamNavTabahrefservicesCommunityServicesadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionConnectwithCamosunliliahrefaboutalumniAlumnialiliahrefservicescooperativeeducationstudentemploymentemployerservicesEmployerServicesaliliahreffoundationFoundationaliliahrefservicescooperativeeducationstudentemploymentcoopemployersHireaCoopStudentaliliahrefinternationalfuturestudentshousinghomestayhosthtmlHomestayFamiliesaliliclasssectionResearchandTrainingliliahrefaboutenterprisepointcontracttraininghtmlContractandCustomizedTrainingaliliahrefaboutenterprisepointEnterprisePointaliliahrefinternationalprogramsprojectscustomizedtraininghtmlGlobalConsultingaliliahrefaboutresearchResearchandInnovationaliuldivdivclasscolumnulclassunstyledliclasssectionHealthServicesliliahreflearnprogramssportexercisetherapyclinichtmlAthleticandExerciseTherapyClinicaliliahrefservicescounsellingcentrecareerhtmlpublicaCareerCounsellingaliliahreflearnschoolhealthhumanservicesdentalclinicDentalClinicaliliahrefsportsfitnessrecreationFitnessandRecreationaliliclasssectionOnCampusliliahrefabouttransportationparkingParkingandMapsaliliahrefservicespurchasingPurchasingandReceivingaliuldivdivclasscolumnulclassunstyledliclasssectionCampusServicesliliahrefhttpcamosuncollegebookstorecaBookstoreiclassiconexternallinktitleLinkonadifferentsiteialiliahrefserviceschildcareChildCarealiliahreflearnprogramsprofessionalcookrestaurantClassRoomRestaurantaliliahrefservicescafeteriaDiningaliliahreflearnprogramshospitalitymanagementdunlophousehtmlDunlopHousealiliahrefservicesfacilitiesservicesemergencymanagementEmergencyManagementaliliahrefservicesfacilityrentalsFacilityRentalsaliliahrefservicesfacilitiesservicesFacilitiesServicesaliliahrefserviceslibraryLibraryaliliahrefservicesprintshopPrintshopaliuldivdivliliclasscamNavTabahrefservicesFormsadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionStudentFormsliliahrefservicesformshtmlapplicationsApplicationFormsaliliahrefservicesformshtmlgradApplytoGraduatealiliahrefservicesformshtmlchangesEnrolmentChangesaliliahrefservicesformshtmltranscriptsEnrolmentLettersaliliahrefservicesformshtmlpermissionFOIPOPReleasealiliahrefinternationalcurrentstudentsformshtmlInternationalStudentFormsaliliahrefservicesformshtmlpermissionPermissionFormsaliliahrefservicesformshtmlgradRequestforCredentialaliliahrefservicesformshtmltranscriptsTranscriptsaliliahrefservicesformshtmltransferTransferCreditaliliahrefservicesformshtmlAllFormsiclassiconchevronrightpadialiuldivdivclasscolumnulclassunstyledliclasssectionOtherFormsliliahreflearnsouthislandpartnershipgettingstartedhtmlDualCreditSIPFormsaliliahrefservicesfacilityrentalsstudentandCCSSroombookinghtmlRoomBookingsStudentsCCSSaliliahrefservicesformshtmlsponsorshipSponsorshipFormsaliuldivdivliliclasscamNavTabahrefinternationalInternationaladivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionProgramsandCostsliliahrefinternationalfuturestudentshousinghomestayhtmlHomestayaliliahrefinternationalfuturestudentsHowtoApplyaliliahrefinternationalprogramsProgramsaliliahrefinternationalwhatitcostshtmlWhatitCostsaliliclasssectionLanguagesliliahrefinternationalindexcnhtmlaliuldivdivclasscolumnulclassunstyledliclasssectionAboutCamosunInternationalliliahrefinternationalfuturestudentsresourceshtmlBrochuresaliliahrefinternationalcontactContactUsaliliahrefinternationalcurrentstudentsCurrentStudentsaliliahrefinternationalcontactagentshtmlEducationAgentsaliliahrefinternationalprogramsprojectscustomizedtraininghtmlGlobalConsultingaliliahrefinternationalstudyabroadStudyAbroadaliuldivdivliliclasscamNavTabahreflearnschoolindigenouseducationcommunityconnectionsIndigenousadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionIndigenousEducationandCommunityConnectionsliliahreflearnschoolindigenouseducationcommunityconnectionsawardsAwardsaliliahreflearnschoolindigenouseducationcommunityconnectionscommunityConnectionwithCommunityaliliahreflearnschoolindigenouseducationcommunityconnectionscontactushtmlContactUsaliliahreflearnschoolindigenouseducationcommunityconnectionsprogramshtmlIndigenousProgramsandCoursesaliliahreflearnschoolindigenouseducationcommunityconnectionsstudentsInfoforStudentsaliuldivdivclasscolumnulclassunstyledliclasssectionAboutIndigenousEducationliliahreflearnschoolindigenouseducationcommunityconnectionsAreYouofIndigenousAncestryaliliahreflearnschoolindigenouseducationcommunityconnectionsabouteducationmodelhtmlEducationalModelaliliahreflearnschoolindigenouseducationcommunityconnectionsaboutTerritoryAcknowledgementaliuldivdivliliclasscamNavTabahrefsportschargersChargersadivclasscamDropDowndivclasscolumnulclassunstyledliclasssectionChargersAthleticsliliahrefsportschargersadoptachargerhtmlAdoptaChargeraliliahrefsportschargersfanzoneGettingtotheGamealiliahrefsportschargersscoreboardScheduleandResultsaliliahrefsportschargersteamsTeamsaliuldivdivliuldivdivdivdividbufferdividcontentclassminimalisthomePagedivclassclearfixdividpagebannerclasshomePagedivclasscontainerimgsrctemplatehelpershelperimagerotatorphpimgdirimageshomepagebannersaltbannersdivdivbrdividpageintroductiondivclasscontainerpclassleadCamosunCollegeislocatedinbeautifulVictoriaBritishColumbiaWeserve18000learnersayearincertificatediplomabachelorsdegreepostdegreediplomaandcontinuingeducationprogramspdivdivdivclasssectiondivclasscontainerdivclassrowequalheightdivclassspan7imagecaptionwrapperahrefceimgsrcimageshomepagenewsimages2016mainCE2016jpgaltNewCECalendarJanuarytoAugust2016divclassimagecaptionimagecaptiondarkh22016ContinuingEducationcalendarisoutsmallsmallh2pExploreyourpassionswithoneofhundredsofcontinuingeducationclassespdivadivdivclassspan5divclasspopboxh2Newsh2ulclassunstyledrsstitlelistliahrefhttpcamosuncanewspressreleases2016januaryfromawarenesstoactionhtmlFromAwarenesstoActionCamosunsStudentMentalHealthandWellbeingStrategyLaunchabrspanclassmutedsmallJanuary2620161121amMediaCentresmallspanliliahrefhttpcamosuncasportschargersnews2016jancamosunwinsbidtohostccaanationalshtmlCamosunwinsbidtohostCCAANationalChampionshipabrspanclassmutedsmallJanuary192016350pmMediaCentresmallspanliulpahrefnewsmediacentreclassbtnbtnminiMediaCentreaph2Eventsh2divclassupcomingeventscompactlistulclassunstyledliclasssummaryahrefeventsdetailhtmluidcalendar3A104743Afielddatetime3A03A40FamilyDayCollegeclosedalilispanclassmutedsmallFeb81200amBothcampusessmallspanliululclassunstyledliclasssummaryahrefeventsdetailhtmluidcalendar3A104753Afielddatetime3A03A39FoundationBursariesDeadlinealilispanclassmutedsmallFeb91200amBothcampusessmallspanliuldivpahrefeventsclassbtnbtnminiCalendarofEventsapdivdivdivdivdivdivclasssectiondivclasscontainerdivclasstilepaneldivclasstileboxdivclasstileboxrowdivclasstiletilegreenahrefservicesadmissionsimgsrcimageshomepagenewsimages2016Apngaltdivclasstilecaptionh4Admissionsh4pGetstartedatCamosunpdivadivdivclasstiletileblueahrefservicesregistrationimgsrcimageshomepagenewsimages2016Rpngaltdivclasstilecaptionh4Registrationh4pForcurrentstudentspdivadivdivdivclasstileboxrowdivclasstiletiledoubletileimageahrefserviceslibraryidcardshtmlimgsrcimageshomepagenewsimages2016camosunid14434772348jpgaltCamosunIDcardsdivclasstilecaptiontilecaptiondarkh4GetyourCamosunIDcardandUPassh4pVisitaUPasskioskorcampuslibrarytorenewpdivadivdivdivclasstileboxrowdivclassmaintileeighthtilewhitepahrefhttpswwwfacebookcomCamosunCollegeimgsrcimageslogosfacebookpngclassicon64altFacebookappahrefhttpstwittercomcamosunimgsrcimageslogostwitterpngclassicon64altTwitterappahrefhttpswwwyoutubecomusermycamosunimgsrcimageslogosyoutubepngclassicon64altYouTubeappahrefaskusclasstrackimgsrcimageshomepagenewsimages2016askuspngaltAskUsclassicon64apdivdivclassmaintilequartertileimageimgsrcimageshomepagenewsimages2016cteifront23453086160jpgaltCentreforTradesEducationandInnovationfrontentrancedivdivclassmaintileeighthtileimageahreflearnprogramsautomotiveservicetechnicianfoundationimgsrcimageshomepagenewsimages2016automotive23639496375jpgaltAutomotiveshopadivdivdivdivclasstileboxdivclasstileboxrowdivclasstiletiledoubletileimageahrefsportschargersimgsrcimageshomepagenewsimages2016rampagemacedo24135404199jpgaltdivclasstilecaptiontilecaptiondarkh4CamosunChargershomegamesh4pJanuary29and30atPISEpdivadivdivdivclasstileboxrowdivclassspan2divclassrowdivclasstiletiledarkgreyahreflearninfosessionsimgsrcimagesiconssquaretileinformationsessionspngaltinformationsessionspngdivclasstilecaptionh4InfoSessionsh4pUpcomingsessionspdivadivdivdivclassrowdivclasstiletileblueahrefservicesfinancialaidawardsbursarieshtmlimgsrcimagesiconssquaretilescholarshipspngaltBursaryapplicationsnowopendivclasstilecaptiontilecaptiondarkh4Applyforabursaryh4pDeadlineisFebruary9pdivadivdivdivdivclassmaintilequartertileimageahrefinternationalimgsrcimageshomepagenewsimages2016international21270247992jpgaltInternationalstudentsadivdivdivclasstileboxrowdivclasstiletiledoubletileimageahrefsportsfitnessrecreationfitnessclassesimgsrcimageshomepagenewsimages2016Fitnessrecstrengthjpgaltdivclasstilecaptiontilecaptiondarkh4Winter2016FitnessandRecreationclassesh4pFromAfternoonHathatoZumbapdivadivdivdivdivclasstileboxdivclasstileboxrowdivclassmaintilehalftileimagepadbottomahrefaboutmentalhealthindexhtmlimgsrcimageshomepagenewsimages2016Head452232371greensquarejpgaltdivclasstilecaptiontilecaptiondarkh3Studentwellbeingstrategyh3pLaunchingJanuary28pdivadivdivclasstiletiledoubletileimageahrefaboutfoundationdonatehtmlimgsrcimageshomepagenewsimages2016givetodaygraphic300x140jpgaltadivdivclasstiletileimageahrefnewspressreleases2016januarycamosunachievesstarssilverratinghtmlimgsrchttpsstarsaasheorgmediacache2b342b34627f3755af441de851582d9675dfpngalt2b34627f3755af441de851582d9675dfpngadivdivclasstiletileimageahrefnewspressreleases2015octobercamosunnamedatop50researchcollegehtmlimgsrcimageshomepagenewsimages2016top50researchcolleges2015jpgaltTop50ResearchColleges2015adivdivdivdivdivdivdividpagefooterclasssectiondivclasscontainerdivclassrowdivclassspan1offset1pahreflearnschoolindigenouseducationcommunityconnectionsaboutindexhtmlimgsrclearnschoolindigenouseducationcommunityconnectionsimagesfneslogotranspngaltfneslogotranspngapdivdivclassspan9emCamosunCollegecampusesarelocatedonthetraditionalterritoriesoftheLkwungenandspanclasssencotenWSNEspanpeoplesWeacknowledgetheirwelcomeandgraciousnesstothestudentswhoseekknowledgehereemdivdivdivdivdivdivdivdividmegaFooterdivclasscontainerdivclassrowdivclassspan6h6ContactUsh6divclassrowdivclassspan3addressstrongCamosunCollegeLansdownestrongbr3100FoulBayRdbrVictoriaBCV8P5J2braddressdivdivclassspan3addressstrongCamosunCollegeInterurbanstrongbr4461InterurbanRdbrVictoriaBCV9E2C1braddressdivdivulclassunstyledliiclassiconphoneiconwhitei2503703000liliiclassiconphoneiconwhitei18775547555tollfreeliuldivdivclassspan3ulclassnavnavlistliclassnavheaderFindPeopleampDepartmentsliliahrefpeoplefindercamosunbccaEmployeeDirectoryaliliahrefaboutdirectoryhtmlPhoneDirectoryaliliahrefnewsmediacentreMediaRelationsaliuldivdivclassspan3ulclassnavnavlistliclassnavheaderInformationForliliahrefservicesadmissionsProspectiveStudentsaliliahrefcurrentCurrentStudentsaliliahrefalumniAlumnialiliahrefaboutfoundationDonorsaliliahrefemployeesEmployeesaliuldivdivdivdivdividfooterdivclasscontainerp19962016CamosunCollegeVictoriaBCCanadaahrefprivacystatementhtmlPrivacystatementaahrefserviceswebteamWebsiteFeedbackapdivdivdividfooterPrinthrp19962016CamosunCollegeVictoriaBCCanadaPrintedJanuary292016at1131amimgsrctemplateimageslogoschangeeverythingprintpngaltChangeEverythinglogoforprintpdivscriptfunctionvarcx01588948496993335032560isdtid8ovargcsedocumentcreateElementscriptgcsetypetextjavascriptgcseasynctruegcsesrcdocumentlocationprotocolhttpshttpshttpwwwgooglecacsecsejscxcxvarsdocumentgetElementsByTagNamescript0sparentNodeinsertBeforegcsesscriptscripttypetextjavascriptsrccdncamosuncajqueryjquerylatestminjsscriptscripttypetextjavascriptsrctemplatejscamosunjsscriptscripttypetextjavascriptvartrackdocumentgetElementsByClassNametrackforxintrackaddListenertrackxclickfunctioneconsolelogesrcElementparentNodehrefifetargethrefundefinedclickIDesrcElementparentNodehrefidesrcElementparentNodeidelseifesrcElementparentNodehrefundefinedclickIDetargethrefidetargetidelseclickIDidetargetidELEMENTPATHepath0tagNameepath1tagNameepath2tagNameepath3tagNameepath4tagNameconsolelogididgaqpushtrackEventCamTrackClickclickIDgasendeventtrackeventclickclickIDfunctionaddListenerelementtypecallbackifelementaddEventListenerelementaddEventListenertypecallbackelseifelementattachEventelementattachEventontypecallbackscriptbodyhtml", string);
	TEST_ASSERT_NULL(error);
	free(string);
}
