/* AUTOGENERATED FILE. DO NOT EDIT. */

//=======Test Runner Used To Run Each Test Below=====
#define RUN_TEST(TestFunc, TestLineNum) \
{ \
  Unity.CurrentTestName = #TestFunc; \
  Unity.CurrentTestLineNumber = TestLineNum; \
  Unity.NumberOfTests++; \
  if (TEST_PROTECT()) \
  { \
      setUp(); \
      TestFunc(); \
  } \
  if (TEST_PROTECT() && !TEST_IS_IGNORED) \
  { \
    tearDown(); \
  } \
  UnityConcludeTest(); \
}

//=======Automagically Detected Files To Include=====
#include "unity.h"
#include <setjmp.h>
#include <stdio.h>
#include "40.h"
#include "io.h"
#include <stdlib.h>

//=======External Functions This Runner Calls=====
extern void setUp(void);
extern void tearDown(void);
extern void test_getInt(void);
extern void test_getLong(void);
extern void test_getUnsigned(void);
extern void test_getFilteredString_valid(void);
extern void test_getFilteredString_invalid(void);
extern void test_getFilteredString_nofilter(void);
extern void test_resorts_valid(void);
extern void test_sortedresorts_valid(void);
extern void test_resorts_invalid(void);


//=======Test Reset Option=====
void resetTest(void);
void resetTest(void)
{
  tearDown();
  setUp();
}


//=======MAIN=====
int main(void)
{
  UnityBegin("40test.c");
  RUN_TEST(test_getInt, 14);
  RUN_TEST(test_getLong, 20);
  RUN_TEST(test_getUnsigned, 26);
  RUN_TEST(test_getFilteredString_valid, 32);
  RUN_TEST(test_getFilteredString_invalid, 41);
  RUN_TEST(test_getFilteredString_nofilter, 50);
  RUN_TEST(test_resorts_valid, 62);
  RUN_TEST(test_sortedresorts_valid, 78);
  RUN_TEST(test_resorts_invalid, 95);

  return (UnityEnd());
}
